-- ═══════════════════════════════════════════════════════════
-- Aegis AI — Migration 00002: Expand Behavioral Baseline (23D)
-- Expands BehavioralBaseline with 23-dimensional biometric feature set
-- ═══════════════════════════════════════════════════════════

ALTER TABLE "BehavioralBaseline"
ADD COLUMN IF NOT EXISTS "keystrokeFlightCV" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "interKeystrokeJitter" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "backspaceRate" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "pauseBeforeFirstKeystroke" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "typingSpeedCPM" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "dwellToFlightRatio" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "mouseAccelerationMean" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "mouseAccelerationStd" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "mouseJerkStd" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "mouseStraightnessIndex" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "mouseAngleChangeRate" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "mousePauseRatio" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "clickToClickDurationMean" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "clickToClickDurationStd" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS "mousePathEfficiency" DOUBLE PRECISION NOT NULL DEFAULT 0.0;
